export default {
    fontFamily: {
        'action-man': ['Action Man', 'sans-serif'],
        'action-man-bold-italic': ['Action Man Bold Italic', 'sans-serif'],
        'action-man-bold': ['Action Man Bold', 'sans-serif'],
        'action-man-extended-bold-italic': ['Action Man Extended Bold Italic', 'sans-serif'],
        'action-man-extended-bold': ['Action Man Extended Bold', 'sans-serif'],
        'action-man-extended-italic': ['Action Man Extended Italic', 'sans-serif'],
        'action-man-extended': ['Action Man Extended', 'sans-serif'],
        'action-man-italic': ['Action Man Italic', 'sans-serif'],
        'action-man-shaded-italic': ['Action Man Shaded Italic', 'sans-serif'],
        'action-man-shaded': ['Action Man Shaded', 'sans-serif'],
        'comic-relief': ['Comic Relief', 'sans-serif'],
        'delius-regular': ['Delius Regular', 'sans-serif'],
        'gloria-hallelujah': ['Gloria Hallelujah', 'cursive'],
        'happy-monkey-regular': ['Happy Monkey Regular', 'sans-serif'],
        'kalam-bold': ['Kalam Bold', 'sans-serif'],
        'kalam-light': ['Kalam Light', 'sans-serif'],
        'kalam-regular': ['Kalam Regular', 'sans-serif'],
        'karatula-bold': ['Karatula Bold', 'sans-serif'],
        'karatula-bold-italic': ['Karatula Bold Italic', 'sans-serif'],
        'karatula-italic': ['Karatula Italic', 'sans-serif'],
        'karatula': ['Karatula', 'sans-serif'],
        'komika-axis': ['Komika Axis', 'sans-serif'],
        'komika-display-bold': ['Komika Display Bold', 'sans-serif'],
        'komika-display-kaps-bold': ['Komika Display Kaps Bold', 'sans-serif'],
        'komika-display-kaps': ['Komika Display Kaps', 'sans-serif'],
        'komika-display': ['Komika Display', 'sans-serif'],
        'komika-hand-bold-italic': ['Komika Hand Bold Italic', 'sans-serif'],
        'komika-hand-bold': ['Komika Hand Bold', 'sans-serif'],
        'komika-hand-italic': ['Komika Hand Italic', 'sans-serif'],
        'komika-hand': ['Komika Hand', 'sans-serif'],
        'komika-hand-parch': ['Komika Hand Parch', 'sans-serif'],
        'komika-text-bold-italic': ['Komika Text Bold Italic', 'sans-serif'],
        'komika-text-bold': ['Komika Text Bold', 'sans-serif'],
        'komika-text-italic': ['Komika Text Italic', 'sans-serif'],
        'komika-text': ['Komika Text', 'sans-serif'],
        'sf-arch-rival-bold-italic': ['SF Arch Rival Bold Italic', 'sans-serif'],
        'sf-arch-rival-bold': ['SF Arch Rival Bold', 'sans-serif'],
        'sf-arch-rival-extended-bold-italic': ['SF Arch Rival Extended Bold Italic', 'sans-serif'],
        'sf-arch-rival-extended-bold': ['SF Arch Rival Extended Bold', 'sans-serif'],
        'sf-arch-rival-extended-italic': ['SF Arch Rival Extended Italic', 'sans-serif'],
        'sf-arch-rival-extended': ['SF Arch Rival Extended', 'sans-serif'],
        'sf-arch-rival-italic': ['SF Arch Rival Italic', 'sans-serif'],
        'sf-arch-rival': ['SF Arch Rival', 'sans-serif'],
        'sf-cartoonist-hand-bold-italic': ['SF Cartoonist Hand Bold Italic', 'sans-serif'],
        'sf-cartoonist-hand-bold': ['SF Cartoonist Hand Bold', 'sans-serif'],
        'sf-cartoonist-hand-italic': ['SF Cartoonist Hand Italic', 'sans-serif'],
        'sf-cartoonist-hand': ['SF Cartoonist Hand', 'sans-serif'],
        'sf-toontime-blotch-italic': ['SF Toontime Blotch Italic', 'sans-serif'],
        'sf-toontime-blotch': ['SF Toontime Blotch', 'sans-serif'],
        'sf-toontime-bold-italic': ['SF Toontime Bold Italic', 'sans-serif'],
        'sf-toontime-bold': ['SF Toontime Bold', 'sans-serif'],
        'sf-toontime-italic': ['SF Toontime Italic', 'sans-serif'],
        'sf-toontime': ['SF Toontime', 'sans-serif'],
        'sf-wonder-comic-blotch-italic': ['SF Wonder Comic Blotch Italic', 'sans-serif'],
        'sf-wonder-comic-blotch': ['SF Wonder Comic Blotch', 'sans-serif'],
        'sf-wonder-comic-bold-italic': ['SF Wonder Comic Bold Italic', 'sans-serif'],
        'sf-wonder-comic-bold': ['SF Wonder Comic Bold', 'sans-serif'],
        'sf-wonder-comic-inline-italic': ['SF Wonder Comic Inline Italic', 'sans-serif'],
        'sf-wonder-comic-inline': ['SF Wonder Comic Inline', 'sans-serif'],
        'sf-wonder-comic-italic': ['SF Wonder Comic Italic', 'sans-serif'],
        'sf-wonder-comic': ['SF Wonder Comic', 'sans-serif'],
        'vtc-letterer-pro': ['VTC Letterer Pro', 'sans-serif'],
        'yew-basturd-bold': ['Yew Basturd Bold', 'sans-serif'],
        'yew-basturd-bold-italic': ['Yew Basturd Bold Italic', 'sans-serif'],
        'yew-basturd-italic': ['Yew Basturd Italic', 'sans-serif'],
        'yew-basturd': ['Yew Basturd', 'sans-serif'],
    }
}